# Generated by Django 3.2.8 on 2021-10-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealProduct',
            new_name='Product',
        ),
    ]
