# Generated by Django 3.2.8 on 2021-11-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='quantity',
            new_name='quantity_in_cart',
        ),
    ]
